print("2.1.8 Caracteres de escape y nueva línea en Python")
print("Pablito clavo un clavito.")
print()
print("En la calva de un calvito.")
print()
print("2.1.9 Usando múltiples argumentos")
print("Pablito" , "clavo" , "un clavito.")
print()
print("2.1.11 Argumentos de palabra clave", end=" ")
print("Mi nombre es", "Saulo", end=" ")
print("Tejeda.")
print()
print("Cuestionario")
print("Mi\nnombre\nes\nBond.", end=" ")
print("James Bond.")