print("2.2 Literales en Python")

print()
print("2.2.1 Literales - los datos en si mismos")
print("Un literal es un valor que se escribe directamente en el codigo.")
print()
print("Ejemplo de literales:")
print("Cadena:", "Hola mundo")
print("Entero:", 123)
print()
print("2.2.2 Enteros")
print("Los enteros son numeros sin parte decimal.")
print("Ejemplos de enteros:")
print(10)
print(-5)
print(11111111)
print(11_111_111)
print()
print("Numeros octales")
print("0o123 en octal equivale a:")
print(0o123)
print()
print("Numeros hexadecimales")
print("0x123 en hexadecimal equivale a:")
print(0x123)
print()
print("2.2.3 Flotantes")
print("Los flotantes tienen parte decimal.")
print("Ejemplos:")
print(2.5)
print(-0.4)
print(4.0)
print(.4)
print(4.)
print()
print("Notacion cientifica")
print("3E8 representa 3 x 10^8")
print(3E8)
print("Constante de Planck:")
print(6.62607E-34)
print()
print("2.2.4 Cadenas")
print("Las cadenas se usan para texto.")
print("Ejemplo:")
print("Yo soy una cadena.")
print()
print("Uso de comillas dentro de cadenas:")
print("Me gusta \"Monty Python\"")
print()
print("Otra forma:")
print('Me gusta "Monty Python"')
print()
print("2.2.5 Valores booleanos")
print("True representa verdadero")
print("False representa falso")
print(True)
print(False)
print()
print("Comparaciones:")
print(True > False)
print(True < False)
print()
print("LAB")
print("\"Estoy\"")
print("\"\"aprendiendo\"\"")
print("\"\"\"Python\"\"\"")